local M = {}

M.icons = {
  diagnostic = {
    error = "",
    warn = "",
    hint = "",
    info = "",
  },
  dap = {
    breakpoint = "󰝥",
    breakpoint_condition = "",
    breakpoint_rejected = "",
    log_point = "",
    stopped = "󰁕",
  },
  lspkind = {
    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "",
    Variable = "",
    Class = "",
    Interface = "",
    Module = "",
    Property = "",
    Unit = "",
    Value = "",
    Enum = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "",
    Event = "",
    Operator = "",
    TypeParameter = "",
  },
}

M.excluded_filetypes = {
  "ClangdAST",
  "DressingInput",
  "Glance",
  "TelescopePrompt",
  "Trouble",
  "checkhealth",
  "dap-repl",
  "dapui_breakpoints",
  "dapui_console",
  "dapui_scopes",
  "dapui_stacks",
  "dapui_watches",
  "edgy",
  "help",
  "lazy",
  "leetcode.nvim",
  "lspinfo",
  "man",
  "mason",
  "minifiles",
  "minifiles-help",
  "noice",
  "notify",
  "qf",
  "sagafinder",
  "sagaoutline",
  "spectre_panel",
  "ssr",
  "toggleterm",
}

M.rainbow_highlight = {
  "RainbowDelimiterRed",
  "RainbowDelimiterYellow",
  "RainbowDelimiterBlue",
  "RainbowDelimiterOrange",
  "RainbowDelimiterGreen",
  "RainbowDelimiterViolet",
  "RainbowDelimiterCyan",
}

return M
