[tools]
bat = "latest"
btop = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
just = "latest"
node = "lts"
opencode = "latest"
ripgrep = "latest"
starship = "latest"
tmux = "latest"
tokei = "latest"
uv = "latest"
yazi = "latest"
zoxide = "latest"
