## enable or disable automatic sync
auto_sync = false

## enable or disable automatic update checks
update_check = false

## which style to use
## possible values: auto, full, compact
style = "full"

## the maximum number of lines the interface should take up
## set it to 0 to always go full screen
inline_height = 30

## Invert the UI - put the search bar at the top , Default to `false`
invert = true

## use ctrl instead of alt as the shortcut modifier key for numerical UI shortcuts
## alt-0 .. alt-9
ctrl_n_shortcuts = true

## Defaults to true. If enabled, upon hitting enter Atuin will immediately execute the command. Press tab to return to the shell and edit.
# This applies for new installs. Old installs will keep the old behaviour unless configured otherwise.
enter_accept = false

## Defaults to false. If enabled, when triggered after && or ||, Atuin will complete commands to chain rather than replace the current line.
command_chaining = true

[stats]
## Set commands where we should consider the subcommand for statistics. Eg, kubectl get vs just kubectl
common_subcommands = [
  "apt",
  "cargo",
  "docker",
  "git",
  "go",
  "ip",
  "nmcli",
  "npm",
  "systemctl",
  "tmux",
]

[keys]
# Defaults to true. If disabled, using the up/down key won't exit the TUI when scrolled past the first/last entry.
scroll_exits = false
# Defaults to true. The left arrow key will exit the TUI when scrolling before the first character
exit_past_line_start = false
# Defaults to true. The right arrow key performs the same functionality as Tab and copies the selected line to the command line to be modified.
accept_past_line_end = false

[preview]
## which preview strategy to use to calculate the preview height (respects max_preview_height).
## possible values: auto, static
## auto: length of the selected command.
## static: length of the longest command stored in the history.
## fixed: use max_preview_height as fixed height.
strategy = "static"
