# : << EOF
set -g status "on"
set -g status-left-style "none"
set -g message-command-style "fg=colour231,bg=colour236"
set -g status-right-style "none"
set -g pane-active-border-style "fg=colour32"
set -g status-style "none,bg=colour235"
set -g message-style "fg=colour231,bg=colour236"
set -g pane-border-style "fg=colour236"
set -g status-right-length "100"
set -g status-left-length "100"
setw -g window-status-activity-style "none"
setw -g window-status-separator ""
setw -g window-status-style "none,fg=colour231,bg=colour235"
set -g status-left "#[fg=colour231,bg=colour32,none] ❐ #S #[fg=colour32,bg=colour235,nobold,nounderscore,noitalics]"
set -g status-right "#{?client_prefix,"⌨",} #{?mouse,"",} #[fg=colour236,bg=colour235,nobold,nounderscore,noitalics]#[fg=colour231,bg=colour236] %R  %d %b #[fg=colour32,bg=colour236,nobold,nounderscore,noitalics]#[fg=colour231,bg=colour32]  #(cut -c3- ~/.dotfiles/tmux/tmux.status.conf | sh -s distro) "
setw -g window-status-format "#[fg=colour231,bg=colour235,none] #I #[fg=colour231,bg=colour235,none] #W "
setw -g window-status-current-format "#[fg=colour235,bg=colour236,nobold,nounderscore,noitalics]#[fg=colour231,bg=colour236,none] #I #[fg=colour231,bg=colour236,none] #W #[fg=colour236,bg=colour235,nobold,nounderscore,noitalics]"

# EOF
#
# online() {
#   /usr/sbin/ping -c 1 www.baidu.com >/dev/null 2>&1 && printf '' || printf ''
# }
#
# distro() {
#   cat /etc/os-release | grep ^NAME | sed -E 's/NAME="(.*)"/\1/g'
# }
#
# "$@"
