Index:
  StandardLibrary: Yes
CompileFlags:
  Add: [
    -Wall,
    -Wextra,
    -Werror,
    -Wshadow,
    -Wnon-virtual-dtor,
    -Wold-style-cast,
    -Wcast-align,
    -Wunused,
    -Woverloaded-virtual,
    -Wpedantic,
    -Wconversion,
    -Wsign-conversion,
    -Wnull-dereference,
    -Wdouble-promotion,
    -Wformat=2,
    -Wimplicit-fallthrough,
  ]
Diagnostics:
  ClangTidy:
    Add: '*'
    Remove: [
      abseil-*,
      altera-*,
      android-*,
      fuchsia-*,
      google-*,
      llvm*,
      modernize-use-trailing-return-type,
      zircon-*,
      readability-else-after-return,
      readability-static-accessed-through-instance,
      readability-avoid-const-params-in-decls,
      cppcoreguidelines-non-private-member-variables-in-classes,
      misc-non-private-member-variables-in-classes,
    ]
  UnusedIncludes: Strict
Completion:
  AllScopes: Yes
Hover:
  ShowAKA: Yes
