If:
  PathMatch: .*\.c
CompileFlags:
  Add: -std=c2x
---
If:
  PathMatch: [
    .*\.cpp,
    .*\.cc,
    .*\.cxx,
    .*\.h,
    .*\.hpp,
    .*\.hxx,
  ]
CompileFlags:
  Add: [
    -std=c++2b,
    -Weffc++,
  ]
---
Index:
  StandardLibrary: Yes
CompileFlags:
  Add: [
    -Wall,
    -Wextra,
  ]
Diagnostics:
  UnusedIncludes: Strict
Completion:
  AllScopes: Yes
Hover:
  ShowAKA: Yes
