check_for_update_on_startup = false
file_opener = "none"
forced_login_method = "chatgpt"
model = "gpt-5.4"
model_reasoning_effort = "high"
personality = "friendly"
plan_mode_reasoning_effort = "high"

[analytics]
enabled = false

[features]
fast_mode = false
memories = true

[feedback]
enabled = false

[plugins."superpowers@openai-curated"]
enabled = true

[tui]
status_line = ["model-with-reasoning", "git-branch", "context-remaining", "five-hour-limit", "weekly-limit"]
theme = "tokyonight_moon"
