disable_response_storage = true
model = "gpt-5-codex"
model_reasoning_effort = "high"

[mcp_servers.context7]
args = ["-y", "@upstash/context7-mcp@latest"]
command = "npx"

[mcp_servers.sequential-thinking]
args = ["-y", "@modelcontextprotocol/server-sequential-thinking"]
command = "npx"
